### ISSUE TITLE
v1 Release

### ISSUE THREAD

**Issue by rowanc1** [curvenote/curvenotejs#48]
- [x] curvenote init
- [x] more logging on the init pull.
- [x] check node version >=14
- [x] check that node 16 works
- [x] check npm version (only on web install) I think anything <8 will fail? need to test.  (@Yxwww says since npm v7)
- [x] ensure oxa IDs are in the repo
- [x] check that init runs without logging in
- [x] Add -v as well as an option

## Init
- [x] your.curve.space --> rowanc1.curve.space
- [x] Remove `Would you like to add additional projects now?`
- [x] Auto pull content
- [x] only say start (not install) 

## Emergent

- [x] choose a license
- [x] remove extra title for our renderer
- [x] get rid of serve
- [x] we are going to deploy things to this website, please confirm.
- [x] issue #59 
- [x] issue #56 
- [x] Export to docx / pdf / latex should work

## Final Changes

 - [x] grey out `Import from Local` `curvenote init` option in all cases
 - [x] grey out `Use Demo content` `curvenote init` option in all cases
 - [x] release v1 to npm 🚀

**Comment by rowanc1** [comment]
![image](https://user-images.githubusercontent.com/913249/162348729-5e8c43db-998a-4fc9-8bff-4dda83b51c69.png)

**Comment by rowanc1** [comment]
- [ ] choose a license

**Comment by rowanc1** [comment]
- [ ] get rid of nulls in author

**Comment by rowanc1** [comment]
- [ ] remove extra title for our renderer

**Comment by rowanc1** [comment]
![image](https://user-images.githubusercontent.com/913249/162349997-26ff462e-b840-4dcb-9edc-15954ce093bd.png)

**Comment by rowanc1** [comment]
- [ ] get rid of `serve`

**Comment by rowanc1** [comment]
- [ ] we are going to deploy things to this website, please confirm.
- [ ] curvenote share [notebook]

**Comment by stevejpurves** [comment]
- [ ] issue #59 
- [ ] issue #56
